name: Gayle Lanier
favicon: null
layout_spectrum: 0.25812
typography_spectrum: 0.25331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020100'
    - '#f5f3ff'
    - '#96a0b6'
    - '#5c4433'
    - '#538dfb'
  brandStrength: 0.1922351128887385
  lightness: 0.8127646902576089
  saturation: 0.6061071546282619
  rhythmicContrast: 0.38885763683356345
purpose: []
